name: finalproj
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  image_picker: ^1.1.2
  tflite_flutter: ^0.10.4
  tflite_v2: 1.0.0
  image: ^3.0.1
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Background.jpg
    - assets/best_float32.tflite
    - images/Background.jpg  # Add your image path here
    - assets/labels.txt
